version: '3.8'

services:
   flask_web_app:
      build:
         context: ./src/img_flask_app
      container_name: ctf_app
      restart: unless-stopped
      network_mode: host
      environment:
         CTF_FLAG: "CHANGE ME"

   nginx_reverse_proxy:
      build:
         context: ./src/img_nginx
      container_name: ctf_rproxy
      restart: unless-stopped
      network_mode: host
      depends_on:
         - flask_web_app
