version: '3.8'

services:
   flask_web_app:
      build:
         context: ./img_flask_app
      container_name: ctf_app
      restart: on-failure
      network_mode: host
      ports:
         - 8000:8000
      environment:
         CTF_FLAG: "Flaggy_McFlagFace"

   nginx_reverse_proxy:
      build:
         context: ./img_nginx
      container_name: ctf_rproxy
      restart: on-failure
      network_mode: host
      ports:
         - 80:80
      depends_on:
         - flask_web_app
