version: "3"

services:
   flask_web_app:
      build:
         context: ./img_flask_app
      container_name: ctf_app
      restart: on-failure

   nginx_reverse_proxy:
      build:
         context: ./img_nginx
      container_name: ctf_rproxy
      restart: on-failure
      ports:
         - 80:80
      depends_on:
         - flask_web_app
